# Form implementation generated from reading ui file '/Users/j0z3ph/Repos/Test/Python/ventana.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(401, 227)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblMensaje = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblMensaje.setGeometry(QtCore.QRect(40, 20, 311, 151))
        self.lblMensaje.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lblMensaje.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.lblMensaje.setText("")
        self.lblMensaje.setWordWrap(True)
        self.lblMensaje.setObjectName("lblMensaje")
        self.btnBoton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnBoton.setGeometry(QtCore.QRect(160, 190, 80, 26))
        self.btnBoton.setObjectName("btnBoton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnBoton.setText(_translate("MainWindow", "Boton"))
